### ISSUE TITLE
Fails to load maxwell.wav due to incorrect path

### ISSUE THREAD

**Issue by Tropingenie** [Oni-Hazza/LC-Toy-Robot-Maxwell-Theme#1]
Installing through Thunderstore using r2modman, the maxwell.wav file is located on a slightly different file path causing the initial call to Load() method to fail. As a workaround, moving `...\Oni_Hazza-ToyRobot_MaxwellTheme\RobotToySound\maxwell.wav` to `...\RobotToySound\maxwell.wav` works, but is not optimal for sharing mod profiles.

**Comment by Oni-Hazza** [comment]
Oh good to know, I never actually used the mod manager. Thanks for letting
me know, I'll sort it out when I next can

**Comment by TheMasterKy** [comment]
![image](https://github.com/Oni-Hazza/LC-Toy-Robot-Maxwell-Theme/assets/146745744/39dac894-fe7f-4128-976b-6246cbbfc12f)
After the newest update 1.1.4 it still cannot locate the .wav file with using r2modman

**Comment by Tropingenie** [comment]
> After the newest update 1.1.4 it still cannot locate the .wav file with using r2modman

Do you see a line "File {p} found" at the INFO level later in the log? That is the expected behaviour right now as I was keeping my changes minimal. As long as the file is found, then the path _should_ be replaced properly during initialization with the correct one.

If you need it, the same log is found at `...\r2modman_data\LethalCompany\profiles\Pon Mod\BepInEx` and you should be able to just ctrl-F for "maxwell.wav" and see if it has the successful message. If you can't find it in the log, then can you tell us where on the file system it is please?

**Comment by Tropingenie** [comment]
In the meantime I have verified on my machine using a clean profile that the change is working as intended:
![image](https://github.com/Oni-Hazza/LC-Toy-Robot-Maxwell-Theme/assets/16670390/81878d1b-ded2-4f66-a346-6f6f650c8a6d)

@TheMasterKy This is what a successful load in 1.1.4 looks like, with the two INFO level messages denoting the second file being found.

**Comment by TheMasterKy** [comment]
Okay thank you. I'll have to look back and check my log. I might have missed it as I have many sounds changed with a sound overhaul mod

**Comment by TheMasterKy** [comment]
Okay so I just re-download the mod to check once again. There is nothing before or after that message for me denoting that a .wav file has been found

**Comment by Oni-Hazza** [comment]
That's very strange, i just installed r2modman to test it myself and it works first time. Is it possible for you to check the files in the r2modman location and see if the maxwell.wav is anywhere to be seen in there?

**Comment by Tropingenie** [comment]
> That's very strange, i just installed r2modman to test it myself and it works first time. Is it possible for you to check the files in the r2modman location and see if the maxwell.wav is anywhere to be seen in there?

From my own testing on some changes in [my fork](https://github.com/Tropingenie/LC-Toy-Robot-Maxwell-Theme), I have run into an issue where r2modman imports maxwell.wav directly into the Oni-Hazza folder, and already have added a check for that there. It wasn't this particular issue, as I couldn't reproduce it using 1.1.4 downloaded off Thunderstore, only my local package.

Regardless, I am waiting to confirm what file path @TheMasterKy has before putting in another pull request, and will add theirs if different from the three potential locations I am aware of.
